/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculadora;

import javax.swing.JOptionPane;

/**
 *
 * @author razvanvc
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    private double factor1, factor2;
    public Calculadora() {
        initComponents();
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        Factor1 = new javax.swing.JTextField();
        Factor2 = new javax.swing.JTextField();
        Resultado = new javax.swing.JTextField();
        Suma = new javax.swing.JButton();
        Resta = new javax.swing.JButton();
        Division = new javax.swing.JButton();
        Multiplicacion = new javax.swing.JButton();
        USD_EUR = new javax.swing.JButton();
        EUR_USD = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Factor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Factor1ActionPerformed(evt);
            }
        });

        Resultado.setEditable(false);
        Resultado.setBackground(new java.awt.Color(204, 204, 204));
        Resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadoActionPerformed(evt);
            }
        });

        Suma.setText("+");
        Suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumaActionPerformed(evt);
            }
        });

        Resta.setText("-");
        Resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestaActionPerformed(evt);
            }
        });

        Division.setText("%");
        Division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivisionActionPerformed(evt);
            }
        });

        Multiplicacion.setText("x");
        Multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplicacionActionPerformed(evt);
            }
        });

        USD_EUR.setText("$->€");
        USD_EUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USD_EURActionPerformed(evt);
            }
        });

        EUR_USD.setText("€->$");
        EUR_USD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EUR_USDActionPerformed(evt);
            }
        });

        jLabel1.setText("Introduce los valores en ambas cajas y haz la opracion que desees");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Resultado)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(281, 281, 281)
                                    .addComponent(Resta, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(281, 281, 281)
                                    .addComponent(EUR_USD)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(Multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Suma, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Factor1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Division, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(USD_EUR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Factor2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Factor2, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(Factor1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Suma)
                    .addComponent(Resta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Division)
                    .addComponent(Multiplicacion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(USD_EUR)
                    .addComponent(EUR_USD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestaActionPerformed
        // TODO add your handling code here:
        try{
        factor1 = Double.parseDouble(Factor1.getText());
        factor2 = Double.parseDouble(Factor2.getText());
        double resultado = factor1 - factor2;
        
        Resultado.setText(String.valueOf(resultado));}catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "ERROR", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_RestaActionPerformed

    private void DivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivisionActionPerformed
        // TODO add your handling code here:
        try{
        factor1 = Double.parseDouble(Factor1.getText());
        factor2 = Double.parseDouble(Factor2.getText());
        if (factor2 == 0){
            JOptionPane.showMessageDialog(this, "ERROR", "Mensaje", JOptionPane.ERROR_MESSAGE);
            Resultado.setText("");
            return;
        }
        double resultado = factor1 / factor2;
        
        Resultado.setText(String.valueOf(resultado));}catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "ERROR", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_DivisionActionPerformed

    private void USD_EURActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USD_EURActionPerformed
        // TODO add your handling code here:
        
        try{
        Resultado.setText(String.valueOf(Double.parseDouble(Resultado.getText())*0.89));}catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "ERROR", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_USD_EURActionPerformed

    private void SumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumaActionPerformed
        // TODO add your handling code here:
        try{
        factor1 = Double.parseDouble(Factor1.getText());
        factor2 = Double.parseDouble(Factor2.getText());
        double resultado = factor1 + factor2;
        
        Resultado.setText(String.valueOf(resultado));}catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "ERROR", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SumaActionPerformed

    private void Factor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Factor1ActionPerformed
        // TODO add your handling code here:
        factor1 = Double.parseDouble(Factor1.getText());
        factor2 = Double.parseDouble(Factor2.getText());
        double resultado = factor1 - factor2;
        
        Resultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_Factor1ActionPerformed

    private void ResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadoActionPerformed
        // TODO add your handling code here:
        try{
        factor1 = Double.parseDouble(Factor1.getText());
        factor2 = Double.parseDouble(Factor2.getText());
        double resultado = factor1 - factor2;
        
        Resultado.setText(String.valueOf(resultado));}catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "ERROR", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ResultadoActionPerformed

    private void EUR_USDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EUR_USDActionPerformed
        // TODO add your handling code here:
        try{
        Resultado.setText(String.valueOf(Double.parseDouble(Resultado.getText())*1.12));}catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "ERROR", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_EUR_USDActionPerformed

    private void MultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicacionActionPerformed
        // TODO add your handling code here:
        try{
        factor1 = Double.parseDouble(Factor1.getText());
        factor2 = Double.parseDouble(Factor2.getText());
        double resultado = factor1 * factor2;
        
        Resultado.setText(String.valueOf(resultado));}catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "ERROR", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_MultiplicacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Division;
    private javax.swing.JButton EUR_USD;
    private javax.swing.JTextField Factor1;
    private javax.swing.JTextField Factor2;
    private javax.swing.JButton Multiplicacion;
    private javax.swing.JButton Resta;
    private javax.swing.JTextField Resultado;
    private javax.swing.JButton Suma;
    private javax.swing.JButton USD_EUR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
